use crate::category::CleanupCategory;
use crate::models::{RiskLevel, TechStack};
use crate::settings::rule::CleanupRule;
use crate::messages::RuleDescription;
use std::sync::LazyLock;

pub fn project_rules() -> &'static [CleanupRule] {
    static RULES: LazyLock<Vec<CleanupRule>> = LazyLock::new(|| {
        vec![
        // Rust
        CleanupRule::project(
            "target",
            TechStack::Rust,
            RiskLevel::Safe,
            CleanupCategory::CompileCache,
            RuleDescription::R001,
        )
        .marker("Cargo.toml"),
        // Node / Web
        CleanupRule::project(
            "node_modules",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::Dependencies,
            RuleDescription::R002,
        )
        .marker("package.json"),
        CleanupRule::project(
            ".next",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R003,
        ),
        CleanupRule::project(
            ".nuxt",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R004,
        ),
        CleanupRule::project(
            ".turbo",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R005,
        ),
        CleanupRule::project(
            ".vite",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R006,
        ),
        CleanupRule::project(
            ".svelte-kit",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R007,
        ),
        CleanupRule::project(
            ".astro",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R008,
        ),
        CleanupRule::project(
            ".angular",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R009,
        ),
        CleanupRule::project(
            ".output",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R010,
        ),
        CleanupRule::project(
            ".vercel",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R011,
        ),
        CleanupRule::project(
            ".netlify",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R012,
        ),
        CleanupRule::project(
            ".expo",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R013,
        ),
        CleanupRule::project(
            ".webpack",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R014,
        ),
        CleanupRule::project(
            "dist",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R015,
        )
        .marker("package.json"),
        CleanupRule::project(
            "build",
            TechStack::NodeWeb,
            RiskLevel::Caution,
            CleanupCategory::BuildOutput,
            RuleDescription::R016,
        )
        .marker("package.json"),
        CleanupRule::project(
            "build",
            TechStack::Android,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R017,
        )
        .marker("build.gradle"),
        CleanupRule::project(
            "build",
            TechStack::Android,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R018,
        )
        .marker("build.gradle.kts"),
        CleanupRule::project(
            ".cache",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::ToolCache,
            RuleDescription::R019,
        ),
        CleanupRule::project(
            ".parcel-cache",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R020,
        ),
        CleanupRule::project(
            "cache",
            TechStack::NodeWeb,
            RiskLevel::Caution,
            CleanupCategory::DependencyCache,
            RuleDescription::R021,
        )
        .marker("package.json")
        .parent(".yarn"),
        CleanupRule::project(
            "coverage",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::TestOutput,
            RuleDescription::R022,
        ),
        CleanupRule::project(
            "htmlcov",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::TestOutput,
            RuleDescription::R023,
        ),
        CleanupRule::project(
            ".nyc_output",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::TestOutput,
            RuleDescription::R024,
        ),
        CleanupRule::project(
            "storybook-static",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R025,
        ),
        // Python
        CleanupRule::project(
            "__pycache__",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::BytecodeCache,
            RuleDescription::R026,
        ),
        CleanupRule::project(
            ".pytest_cache",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::TestCache,
            RuleDescription::R027,
        ),
        CleanupRule::project(
            ".mypy_cache",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::TypeCheckCache,
            RuleDescription::R028,
        ),
        CleanupRule::project(
            ".ruff_cache",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::LintCache,
            RuleDescription::R029,
        ),
        CleanupRule::project(
            ".tox",
            TechStack::Python,
            RiskLevel::Caution,
            CleanupCategory::TestEnv,
            RuleDescription::R030,
        ),
        CleanupRule::project(
            ".nox",
            TechStack::Python,
            RiskLevel::Caution,
            CleanupCategory::TestEnv,
            RuleDescription::R031,
        ),
        CleanupRule::project(
            ".eggs",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R032,
        ),
        CleanupRule::project(
            ".hypothesis",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::TestCache,
            RuleDescription::R033,
        ),
        CleanupRule::project(
            "",
            TechStack::Python,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R034,
        )
        .prefix("*.egg-info"),
        CleanupRule::project(
            ".venv",
            TechStack::Python,
            RiskLevel::Caution,
            CleanupCategory::VirtualEnv,
            RuleDescription::R035,
        ),
        CleanupRule::project(
            "venv",
            TechStack::Python,
            RiskLevel::Caution,
            CleanupCategory::VirtualEnv,
            RuleDescription::R035,
        ),
        // Go / Ruby / PHP
        CleanupRule::project(
            "vendor",
            TechStack::Go,
            RiskLevel::Caution,
            CleanupCategory::Dependency,
            RuleDescription::R036,
        )
        .marker("go.mod"),
        CleanupRule::project(
            "vendor",
            TechStack::Php,
            RiskLevel::Caution,
            CleanupCategory::Dependency,
            RuleDescription::R037,
        )
        .marker("composer.json"),
        CleanupRule::project(
            "bundle",
            TechStack::Ruby,
            RiskLevel::Caution,
            CleanupCategory::Dependency,
            RuleDescription::R038,
        )
        .marker("Gemfile")
        .parent("vendor"),
        // Java / Android / KMP
        CleanupRule::project(
            ".gradle",
            TechStack::Android,
            RiskLevel::Caution,
            CleanupCategory::GradleCache,
            RuleDescription::R039,
        ),
        CleanupRule::project(
            "app/build",
            TechStack::Android,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R040,
        ),
        CleanupRule::project(
            "target",
            TechStack::Java,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R041,
        )
        .marker("pom.xml"),
        // iOS
        CleanupRule::project(
            "Pods",
            TechStack::Ios,
            RiskLevel::Caution,
            CleanupCategory::Dependency,
            RuleDescription::R042,
        ),
        CleanupRule::project(
            "DerivedData",
            TechStack::Ios,
            RiskLevel::Safe,
            CleanupCategory::XcodeCache,
            RuleDescription::R043,
        ),
        // Flutter
        CleanupRule::project(
            ".dart_tool",
            TechStack::Flutter,
            RiskLevel::Safe,
            CleanupCategory::ToolCache,
            RuleDescription::R044,
        ),
        CleanupRule::project(
            ".flutter-plugins-dependencies",
            TechStack::Flutter,
            RiskLevel::Safe,
            CleanupCategory::PluginCache,
            RuleDescription::R045,
        ),
        // .NET
        CleanupRule::project(
            "bin",
            TechStack::DotNet,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R046,
        )
        .marker("*.csproj"),
        CleanupRule::project(
            "obj",
            TechStack::DotNet,
            RiskLevel::Safe,
            CleanupCategory::IntermediateOutput,
            RuleDescription::R047,
        )
        .marker("*.csproj"),
        // C/C++
        CleanupRule::project(
            "",
            TechStack::Cpp,
            RiskLevel::Safe,
            CleanupCategory::BuildDir,
            RuleDescription::R048,
        )
        .prefix("cmake-build-"),
        CleanupRule::project(
            "out",
            TechStack::Cpp,
            RiskLevel::Safe,
            CleanupCategory::BuildDir,
            RuleDescription::R049,
        )
        .marker("CMakeLists.txt"),
        CleanupRule::project(
            "zig-cache",
            TechStack::Cpp,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R050,
        )
        .marker("build.zig"),
        CleanupRule::project(
            "zig-out",
            TechStack::Cpp,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R051,
        )
        .marker("build.zig"),
        // Unity
        CleanupRule::project(
            "Library",
            TechStack::Unity,
            RiskLevel::Safe,
            CleanupCategory::BuildCache,
            RuleDescription::R052,
        )
        .marker("ProjectSettings/ProjectVersion.txt"),
        CleanupRule::project(
            "Temp",
            TechStack::Unity,
            RiskLevel::Safe,
            CleanupCategory::TempFiles,
            RuleDescription::R053,
        )
        .marker("ProjectSettings/ProjectVersion.txt"),
        CleanupRule::project(
            "Logs",
            TechStack::Unity,
            RiskLevel::Safe,
            CleanupCategory::Logs,
            RuleDescription::R054,
        )
        .marker("ProjectSettings/ProjectVersion.txt"),
        // Godot
        CleanupRule::project(
            ".godot",
            TechStack::Other,
            RiskLevel::Safe,
            CleanupCategory::EditorCache,
            RuleDescription::R055,
        )
        .marker("project.godot"),
        // Terraform
        CleanupRule::project(
            ".terraform",
            TechStack::Infra,
            RiskLevel::Caution,
            CleanupCategory::ProviderCache,
            RuleDescription::R056,
        ),
        // Elixir
        CleanupRule::project(
            "_build",
            TechStack::Other,
            RiskLevel::Safe,
            CleanupCategory::BuildOutput,
            RuleDescription::R057,
        )
        .marker("mix.exs"),
        CleanupRule::project(
            ".cache",
            TechStack::NodeWeb,
            RiskLevel::Safe,
            CleanupCategory::ToolCache,
            RuleDescription::R058,
        )
        .marker("package.json")
        .parent("node_modules"),
        CleanupRule::project(
            "deps",
            TechStack::Other,
            RiskLevel::Caution,
            CleanupCategory::Dependency,
            RuleDescription::R059,
        )
        .marker("mix.exs"),
        ]
    });
    RULES.as_slice()
}
