#!/usr/bin/env python3
"""Generate RuleDescription enum from rule sources + translation table.

Usage (from repo root):
  python3 scripts/generate-rule-descriptions.py          # regenerate enum only
  python3 scripts/generate-rule-descriptions.py --patch  # also patch zh strings in rules
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = ROOT / "crates/clv-core/src"
SOURCES = [
    CORE / "settings/project_rules.rs",
    CORE / "settings/global_rules.rs",
    CORE / "agent_sessions.rs",
]
OUT = CORE / "messages/rule_description.rs"
TRANSLATIONS = Path(__file__).with_name("rule-description-translations.json")

PATTERN = re.compile(r'(CleanupCategory::\w+,\s*\n\s*)"([^"]+)",', re.MULTILINE)

TAIL = """
const ALL_LANGUAGES: [Language; 3] = [Language::Zh, Language::En, Language::Ja];

pub fn rule_description_matches_query(description: RuleDescription, query: &str) -> bool {
    ALL_LANGUAGES.iter().any(|&lang| {
        description.text(lang).to_lowercase().contains(query)
    })
}
"""


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load_translations() -> dict[str, tuple[str, str]]:
    data = json.loads(TRANSLATIONS.read_text(encoding="utf-8"))
    out: dict[str, tuple[str, str]] = {}
    for zh, pair in data.items():
        if not isinstance(pair, list) or len(pair) != 2:
            raise ValueError(f"bad translation entry for {zh!r}")
        out[zh] = (pair[0], pair[1])
    return out


def collect_descriptions(translations: dict[str, tuple[str, str]]) -> list[str]:
    """Stable order follows scripts/rule-description-translations.json."""
    return list(translations.keys())


def variant_name(index: int) -> str:
    return f"R{index:03d}"


def generate_enum(descriptions: list[str], translations: dict[str, tuple[str, str]]) -> str:
    missing = [d for d in descriptions if d not in translations]
    if missing:
        print("Missing translations:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        raise SystemExit(1)

    extra = set(translations) - set(descriptions)
    if extra:
        print(f"Warning: {len(extra)} unused translation(s) in JSON", file=sys.stderr)

    lines = [
        "// AUTO-GENERATED by scripts/generate-rule-descriptions.py — do not edit.",
        "// Translations: scripts/rule-description-translations.json",
        "",
        "use crate::locale::{Language, tr};",
        "use serde::{Deserialize, Serialize};",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]",
        "#[serde(rename_all = \"snake_case\")]",
        "pub enum RuleDescription {",
    ]
    for i, _zh in enumerate(descriptions, start=1):
        lines.append(f"    {variant_name(i)},")
    lines.append("}")
    lines.append("")
    lines.append("impl RuleDescription {")
    lines.append("    pub const ALL: &'static [RuleDescription] = &[")
    for i in range(1, len(descriptions) + 1):
        lines.append(f"        Self::{variant_name(i)},")
    lines.append("    ];")
    lines.append("")
    lines.append("    pub fn text(self, lang: Language) -> &'static str {")
    lines.append("        use RuleDescription::*;")
    lines.append("        match self {")
    for i, zh in enumerate(descriptions, start=1):
        en, ja = translations[zh]
        lines.append(
            f"            {variant_name(i)} => tr(lang, {rust_str(zh)}, {rust_str(en)}, {rust_str(ja)}),"
        )
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + TAIL


def patch_sources(zh_to_variant: dict[str, str]) -> None:
    for path in SOURCES:
        text = path.read_text(encoding="utf-8")

        def repl(m: re.Match[str]) -> str:
            zh = m.group(2)
            if zh.startswith("RuleDescription::"):
                return m.group(0)
            return f'{m.group(1)}RuleDescription::{zh_to_variant[zh]},'

        new_text = PATTERN.sub(repl, text)
        if "use crate::messages::RuleDescription;" not in new_text:
            if path.name == "agent_sessions.rs":
                anchor = "use crate::messages::RuleDescription;\n"
                if anchor not in new_text:
                    new_text = new_text.replace(
                        "use crate::category::CleanupCategory;\n",
                        "use crate::category::CleanupCategory;\nuse crate::messages::RuleDescription;\n",
                    )
            else:
                new_text = new_text.replace(
                    "use crate::settings::rule::CleanupRule;\n",
                    "use crate::settings::rule::CleanupRule;\nuse crate::messages::RuleDescription;\n",
                )
        path.write_text(new_text, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--patch", action="store_true", help="patch rule source files")
    args = parser.parse_args()

    translations = load_translations()
    descriptions = collect_descriptions(translations)
    zh_to_variant = {zh: variant_name(i + 1) for i, zh in enumerate(descriptions)}

    body = generate_enum(descriptions, translations)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body + "\n", encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)} ({len(descriptions)} variants)")

    if args.patch:
        patch_sources(zh_to_variant)
        print(f"Patched {len(SOURCES)} rule source files")


if __name__ == "__main__":
    main()
